name: Maven Build And Deploy to Azure Spring Apps With Artifact
on: workflow_dispatch
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: 471cca20-96cf-49ce-b242-4e67f0e14e19
  AZURE_SPRING_APPS_SERRVICE_NAME: azure-spring-apps-221207
  AZURE_SPRING_APPS_APP_NAME: azure-spring-apps-app-221207

jobs:
  maven_build_and_deploy_to_azure_spring_apps_with_artifact:
    runs-on: ubuntu-latest
    name: Maven Build And Deploy to Azure Spring Apps With Artifact
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy to production with artifact
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: ${{ env.AZURE_SPRING_APPS_SERRVICE_NAME }}
          app-name: ${{ env.AZURE_SPRING_APPS_APP_NAME }}
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}/**/*.jar
